version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FOLDER_ID=${FOLDER_ID:-your_folder_id}
      - API_KEY=${API_KEY:-your_api_key}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis-data: